version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: hotel-db
    ports:
      - "27017:27017"

  rest-api:
    build: .
    container_name: rest-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/hotel-db
      - spring.data.mongodb.database=hotel-db
